/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentsAdminDashboardContentHeader: typeof import('./views/components/admin/dashboard/contentHeader.vue')['default']
    ComponentsAdminDashboardModalEvaluation: typeof import('./views/components/admin/dashboard/modalEvaluation.vue')['default']
    ComponentsAdminFooter: typeof import('./views/components/admin/Footer.vue')['default']
    ComponentsAdminHeader: typeof import('./views/components/admin/Header.vue')['default']
    ComponentsAdminSidebar: typeof import('./views/components/admin/Sidebar.vue')['default']
    ComponentsEMTTitle: typeof import('./views/components/EMTTitle.vue')['default']
    ComponentsHelloWorld: typeof import('./views/components/HelloWorld.vue')['default']
    ComponentsImageUploader: typeof import('./views/components/ImageUploader.vue')['default']
    ComponentsLoader: typeof import('./views/components/Loader.vue')['default']
    ComponentsQuillEditor: typeof import('./views/components/QuillEditor.vue')['default']
    ComponentsSplash: typeof import('./views/components/Splash.vue')['default']
    ComponentsUserFooter: typeof import('./views/components/user/Footer.vue')['default']
    ComponentsUserHeader: typeof import('./views/components/user/Header.vue')['default']
    LayoutsAdmin: typeof import('./views/layouts/Admin.vue')['default']
    LayoutsAdminDashboard: typeof import('./views/layouts/admin/Dashboard.vue')['default']
    LayoutsUser: typeof import('./views/layouts/User.vue')['default']
    Pages404: typeof import('./views/pages/404.vue')['default']
    PagesAdminAuthLogin: typeof import('./views/pages/admin/auth/Login.vue')['default']
    PagesAdminAuthRegistration: typeof import('./views/pages/admin/auth/Registration.vue')['default']
    PagesAdminDashboardEditContent: typeof import('./views/pages/admin/dashboard/editContent.vue')['default']
    PagesAdminDashboardManageApplicationContent: typeof import('./views/pages/admin/dashboard/ManageApplicationContent.vue')['default']
    PagesAdminDashboardManageContent: typeof import('./views/pages/admin/dashboard/ManageContent.vue')['default']
    PagesAdminDashboardManageFinalEvaluation: typeof import('./views/pages/admin/dashboard/ManageFinalEvaluation.vue')['default']
    PagesAdminDashboardManageLearningMaterials: typeof import('./views/pages/admin/dashboard/ManageLearningMaterials.vue')['default']
    PagesAdminDashboardManageStudent: typeof import('./views/pages/admin/dashboard/ManageStudent.vue')['default']
    PagesAdminDashboardOverview: typeof import('./views/pages/admin/dashboard/Overview.vue')['default']
    PagesAdminDashboardStudentDetail: typeof import('./views/pages/admin/dashboard/StudentDetail.vue')['default']
    PagesUserAuthGetStarted: typeof import('./views/pages/user/auth/GetStarted.vue')['default']
    PagesUserAuthLanding: typeof import('./views/pages/user/auth/Landing.vue')['default']
    PagesUserAuthLogin: typeof import('./views/pages/user/auth/Login.vue')['default']
    PagesUserGamePlayEvaluation: typeof import('./views/pages/user/gamePlay/Evaluation.vue')['default']
    PagesUserGamePlayFinalEvaluation: typeof import('./views/pages/user/gamePlay/FinalEvaluation.vue')['default']
    PagesUserGamePlayMenu: typeof import('./views/pages/user/gamePlay/Menu.vue')['default']
    PagesUserGamePlayPlay: typeof import('./views/pages/user/gamePlay/Play.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
